- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start services
  ansible.builtin.service:
    name: mysql 
    enabled: yes 
    state: started

- name: password setup for mysql
  ansible.builtin.command: mysql_secure_installation --set-root-pass Roboshop@1
  